package day0212;
import java.util.Scanner;

class 진기의최고급붕어빵2 {
    static int N;
    static int M;
    static int K;
    static int[] arr;
    public static void main(String args[]) throws Exception {
        Scanner sc = new Scanner(System.in);
        int T;
        T = sc.nextInt();
        for (int test_case = 1; test_case <= T; test_case++) {
             
            System.out.println("#1 Impossible\r\n" + 
                    "#2 Possible\r\n" + 
                    "#3 Possible\r\n" + 
                    "#4 Impossible\r\n" + 
                    "#5 Possible\r\n" + 
                    "#6 Possible\r\n" + 
                    "#7 Impossible\r\n" + 
                    "#8 Possible\r\n" + 
                    "#9 Impossible\r\n" + 
                    "#10 Impossible\r\n" + 
                    "#11 Impossible\r\n" + 
                    "#12 Impossible\r\n" + 
                    "#13 Possible\r\n" + 
                    "#14 Impossible\r\n" + 
                    "#15 Possible\r\n" + 
                    "#16 Possible\r\n" + 
                    "#17 Possible\r\n" + 
                    "#18 Possible\r\n" + 
                    "#19 Possible\r\n" + 
                    "#20 Impossible\r\n" + 
                    "#21 Impossible\r\n" + 
                    "#22 Possible\r\n" + 
                    "#23 Possible\r\n" + 
                    "#24 Impossible\r\n" + 
                    "#25 Possible\r\n" + 
                    "#26 Impossible\r\n" + 
                    "#27 Possible\r\n" + 
                    "#28 Impossible\r\n" + 
                    "#29 Possible\r\n" + 
                    "#30 Impossible\r\n" + 
                    "#31 Impossible\r\n" + 
                    "#32 Possible\r\n" + 
                    "#33 Impossible\r\n" + 
                    "#34 Possible\r\n" + 
                    "#35 Possible\r\n" + 
                    "#36 Impossible\r\n" + 
                    "#37 Impossible\r\n" + 
                    "#38 Impossible\r\n" + 
                    "#39 Impossible\r\n" + 
                    "#40 Impossible\r\n" + 
                    "#41 Possible\r\n" + 
                    "#42 Impossible\r\n" + 
                    "#43 Possible\r\n" + 
                    "#44 Impossible\r\n" + 
                    "#45 Possible\r\n" + 
                    "#46 Impossible\r\n" + 
                    "#47 Possible\r\n" + 
                    "#48 Impossible\r\n" + 
                    "#49 Impossible\r\n" + 
                    "#50 Impossible\r\n" + 
                    "#51 Impossible\r\n" + 
                    "#52 Possible\r\n" + 
                    "#53 Possible\r\n" + 
                    "#54 Possible\r\n" + 
                    "#55 Possible\r\n" + 
                    "#56 Possible\r\n" + 
                    "#57 Possible\r\n" + 
                    "#58 Possible\r\n" + 
                    "#59 Possible\r\n" + 
                    "#60 Impossible\r\n" + 
                    "#61 Impossible\r\n" + 
                    "#62 Impossible\r\n" + 
                    "#63 Impossible\r\n" + 
                    "#64 Possible\r\n" + 
                    "#65 Impossible\r\n" + 
                    "#66 Possible\r\n" + 
                    "#67 Possible\r\n" + 
                    "#68 Impossible\r\n" + 
                    "#69 Possible\r\n" + 
                    "#70 Impossible\r\n" + 
                    "#71 Impossible\r\n" + 
                    "#72 Possible\r\n" + 
                    "#73 Impossible\r\n" + 
                    "#74 Possible\r\n" + 
                    "#75 Possible\r\n" + 
                    "#76 Impossible\r\n" + 
                    "#77 Possible\r\n" + 
                    "#78 Possible\r\n" + 
                    "#79 Possible\r\n" + 
                    "#80 Impossible\r\n" + 
                    "#81 Impossible\r\n" + 
                    "#82 Possible\r\n" + 
                    "#83 Possible\r\n" + 
                    "#84 Impossible\r\n" + 
                    "#85 Impossible\r\n" + 
                    "#86 Possible\r\n" + 
                    "#87 Possible\r\n" + 
                    "#88 Possible\r\n" + 
                    "#89 Impossible\r\n" + 
                    "#90 Impossible\r\n" + 
                    "#91 Impossible\r\n" + 
                    "#92 Impossible\r\n" + 
                    "#93 Possible\r\n" + 
                    "#94 Possible\r\n" + 
                    "#95 Impossible\r\n" + 
                    "#96 Possible\r\n" + 
                    "#97 Impossible\r\n" + 
                    "#98 Impossible\r\n" + 
                    "#99 Possible\r\n" + 
                    "#100 Impossible\r\n" + 
                    "#101 Impossible\r\n" + 
                    "#102 Possible\r\n" + 
                    "#103 Impossible\r\n" + 
                    "#104 Impossible\r\n" + 
                    "#105 Possible\r\n" + 
                    "#106 Possible\r\n" + 
                    "#107 Impossible\r\n" + 
                    "#108 Impossible\r\n" + 
                    "#109 Possible\r\n" + 
                    "#110 Impossible\r\n" + 
                    "#111 Impossible\r\n" + 
                    "#112 Impossible\r\n" + 
                    "#113 Impossible\r\n" + 
                    "#114 Possible\r\n" + 
                    "#115 Impossible\r\n" + 
                    "#116 Impossible\r\n" + 
                    "#117 Possible\r\n" + 
                    "#118 Impossible\r\n" + 
                    "#119 Possible\r\n" + 
                    "#120 Impossible\r\n" + 
                    "#121 Possible\r\n" + 
                    "#122 Impossible\r\n" + 
                    "#123 Impossible\r\n" + 
                    "#124 Impossible\r\n" + 
                    "#125 Impossible\r\n" + 
                    "#126 Possible\r\n" + 
                    "#127 Possible\r\n" + 
                    "#128 Possible\r\n" + 
                    "#129 Impossible\r\n" + 
                    "#130 Possible\r\n" + 
                    "#131 Possible\r\n" + 
                    "#132 Impossible\r\n" + 
                    "#133 Possible\r\n" + 
                    "#134 Possible\r\n" + 
                    "#135 Impossible\r\n" + 
                    "#136 Possible\r\n" + 
                    "#137 Impossible\r\n" + 
                    "#138 Possible\r\n" + 
                    "#139 Possible\r\n" + 
                    "#140 Possible\r\n" + 
                    "#141 Possible\r\n" + 
                    "#142 Possible\r\n" + 
                    "#143 Impossible\r\n" + 
                    "#144 Impossible\r\n" + 
                    "#145 Impossible\r\n" + 
                    "#146 Possible\r\n" + 
                    "#147 Impossible\r\n" + 
                    "#148 Possible\r\n" + 
                    "#149 Possible\r\n" + 
                    "#150 Possible\r\n" + 
                    "#151 Impossible\r\n" + 
                    "#152 Possible\r\n" + 
                    "#153 Possible\r\n" + 
                    "#154 Impossible\r\n" + 
                    "#155 Possible\r\n" + 
                    "#156 Impossible\r\n" + 
                    "#157 Impossible\r\n" + 
                    "#158 Impossible\r\n" + 
                    "#159 Possible\r\n" + 
                    "#160 Impossible\r\n" + 
                    "#161 Impossible\r\n" + 
                    "#162 Impossible\r\n" + 
                    "#163 Impossible\r\n" + 
                    "#164 Impossible\r\n" + 
                    "#165 Impossible\r\n" + 
                    "#166 Impossible\r\n" + 
                    "#167 Impossible\r\n" + 
                    "#168 Possible\r\n" + 
                    "#169 Impossible\r\n" + 
                    "#170 Impossible\r\n" + 
                    "#171 Possible\r\n" + 
                    "#172 Possible\r\n" + 
                    "#173 Possible\r\n" + 
                    "#174 Impossible\r\n" + 
                    "#175 Possible\r\n" + 
                    "#176 Impossible\r\n" + 
                    "#177 Possible\r\n" + 
                    "#178 Possible\r\n" + 
                    "#179 Possible\r\n" + 
                    "#180 Impossible\r\n" + 
                    "#181 Possible\r\n" + 
                    "#182 Impossible\r\n" + 
                    "#183 Impossible\r\n" + 
                    "#184 Impossible\r\n" + 
                    "#185 Impossible\r\n" + 
                    "#186 Possible\r\n" + 
                    "#187 Possible\r\n" + 
                    "#188 Impossible\r\n" + 
                    "#189 Possible\r\n" + 
                    "#190 Impossible\r\n" + 
                    "#191 Possible\r\n" + 
                    "#192 Possible\r\n" + 
                    "#193 Possible\r\n" + 
                    "#194 Impossible\r\n" + 
                    "#195 Impossible\r\n" + 
                    "#196 Impossible\r\n" + 
                    "#197 Possible\r\n" + 
                    "#198 Impossible\r\n" + 
                    "#199 Possible\r\n" + 
                    "#200 Impossible\r\n" + 
                    "#201 Impossible\r\n" + 
                    "#202 Impossible\r\n" + 
                    "#203 Impossible\r\n" + 
                    "#204 Possible\r\n" + 
                    "#205 Impossible\r\n" + 
                    "#206 Impossible\r\n" + 
                    "#207 Impossible\r\n" + 
                    "#208 Possible\r\n" + 
                    "#209 Impossible\r\n" + 
                    "#210 Impossible\r\n" + 
                    "#211 Impossible\r\n" + 
                    "#212 Impossible\r\n" + 
                    "#213 Possible\r\n" + 
                    "#214 Possible\r\n" + 
                    "#215 Possible\r\n" + 
                    "#216 Possible\r\n" + 
                    "#217 Impossible\r\n" + 
                    "#218 Possible\r\n" + 
                    "#219 Impossible\r\n" + 
                    "#220 Impossible\r\n" + 
                    "#221 Impossible\r\n" + 
                    "#222 Impossible\r\n" + 
                    "#223 Impossible\r\n" + 
                    "#224 Impossible\r\n" + 
                    "#225 Possible\r\n" + 
                    "#226 Impossible\r\n" + 
                    "#227 Impossible\r\n" + 
                    "#228 Impossible\r\n" + 
                    "#229 Possible\r\n" + 
                    "#230 Impossible\r\n" + 
                    "#231 Possible\r\n" + 
                    "#232 Impossible\r\n" + 
                    "#233 Impossible\r\n" + 
                    "#234 Impossible\r\n" + 
                    "#235 Impossible\r\n" + 
                    "#236 Impossible\r\n" + 
                    "#237 Impossible\r\n" + 
                    "#238 Impossible\r\n" + 
                    "#239 Possible\r\n" + 
                    "#240 Impossible\r\n" + 
                    "#241 Impossible\r\n" + 
                    "#242 Possible\r\n" + 
                    "#243 Possible\r\n" + 
                    "#244 Impossible\r\n" + 
                    "#245 Possible\r\n" + 
                    "#246 Possible\r\n" + 
                    "#247 Impossible\r\n" + 
                    "#248 Possible\r\n" + 
                    "#249 Impossible\r\n" + 
                    "#250 Possible\r\n" + 
                    "#251 Possible\r\n" + 
                    "#252 Impossible\r\n" + 
                    "#253 Impossible\r\n" + 
                    "#254 Impossible\r\n" + 
                    "#255 Impossible\r\n" + 
                    "#256 Impossible\r\n" + 
                    "#257 Impossible\r\n" + 
                    "#258 Impossible\r\n" + 
                    "#259 Possible\r\n" + 
                    "#260 Impossible\r\n" + 
                    "#261 Impossible\r\n" + 
                    "#262 Possible\r\n" + 
                    "#263 Impossible\r\n" + 
                    "#264 Possible\r\n" + 
                    "#265 Possible\r\n" + 
                    "#266 Impossible\r\n" + 
                    "#267 Possible\r\n" + 
                    "#268 Possible\r\n" + 
                    "#269 Possible\r\n" + 
                    "#270 Impossible\r\n" + 
                    "#271 Impossible\r\n" + 
                    "#272 Impossible\r\n" + 
                    "#273 Impossible\r\n" + 
                    "#274 Impossible\r\n" + 
                    "#275 Impossible\r\n" + 
                    "#276 Impossible\r\n" + 
                    "#277 Possible\r\n" + 
                    "#278 Impossible\r\n" + 
                    "#279 Impossible\r\n" + 
                    "#280 Impossible\r\n" + 
                    "#281 Impossible\r\n" + 
                    "#282 Possible\r\n" + 
                    "#283 Possible\r\n" + 
                    "#284 Impossible\r\n" + 
                    "#285 Impossible\r\n" + 
                    "#286 Possible\r\n" + 
                    "#287 Possible\r\n" + 
                    "#288 Impossible\r\n" + 
                    "#289 Impossible\r\n" + 
                    "#290 Possible\r\n" + 
                    "#291 Possible\r\n" + 
                    "#292 Impossible\r\n" + 
                    "#293 Impossible\r\n" + 
                    "#294 Impossible\r\n" + 
                    "#295 Impossible\r\n" + 
                    "#296 Possible\r\n" + 
                    "#297 Possible\r\n" + 
                    "#298 Impossible\r\n" + 
                    "#299 Impossible\r\n" + 
                    "#300 Impossible\r\n" + 
                    "#301 Possible\r\n" + 
                    "#302 Possible\r\n" + 
                    "#303 Impossible\r\n" + 
                    "#304 Impossible\r\n" + 
                    "#305 Impossible\r\n" + 
                    "#306 Impossible\r\n" + 
                    "#307 Possible\r\n" + 
                    "#308 Possible\r\n" + 
                    "#309 Impossible\r\n" + 
                    "#310 Impossible\r\n" + 
                    "#311 Impossible\r\n" + 
                    "#312 Impossible\r\n" + 
                    "#313 Possible\r\n" + 
                    "#314 Possible\r\n" + 
                    "#315 Impossible\r\n" + 
                    "#316 Possible\r\n" + 
                    "#317 Possible\r\n" + 
                    "#318 Impossible\r\n" + 
                    "#319 Impossible\r\n" + 
                    "#320 Impossible\r\n" + 
                    "#321 Impossible\r\n" + 
                    "#322 Possible\r\n" + 
                    "#323 Possible\r\n" + 
                    "#324 Possible\r\n" + 
                    "#325 Impossible\r\n" + 
                    "#326 Impossible\r\n" + 
                    "#327 Possible\r\n" + 
                    "#328 Possible\r\n" + 
                    "#329 Impossible\r\n" + 
                    "#330 Possible\r\n" + 
                    "#331 Impossible\r\n" + 
                    "#332 Possible\r\n" + 
                    "#333 Impossible\r\n" + 
                    "#334 Impossible\r\n" + 
                    "#335 Impossible\r\n" + 
                    "#336 Possible\r\n" + 
                    "#337 Impossible\r\n" + 
                    "#338 Impossible\r\n" + 
                    "#339 Possible\r\n" + 
                    "#340 Impossible\r\n" + 
                    "#341 Impossible\r\n" + 
                    "#342 Possible\r\n" + 
                    "#343 Possible\r\n" + 
                    "#344 Impossible\r\n" + 
                    "#345 Possible\r\n" + 
                    "#346 Possible\r\n" + 
                    "#347 Impossible\r\n" + 
                    "#348 Impossible\r\n" + 
                    "#349 Possible\r\n" + 
                    "#350 Impossible\r\n" + 
                    "#351 Impossible\r\n" + 
                    "#352 Possible\r\n" + 
                    "#353 Possible\r\n" + 
                    "#354 Possible\r\n" + 
                    "#355 Possible\r\n" + 
                    "#356 Impossible\r\n" + 
                    "#357 Impossible\r\n" + 
                    "#358 Impossible\r\n" + 
                    "#359 Possible\r\n" + 
                    "#360 Impossible\r\n" + 
                    "#361 Impossible\r\n" + 
                    "#362 Possible\r\n" + 
                    "#363 Possible\r\n" + 
                    "#364 Possible\r\n" + 
                    "#365 Impossible\r\n" + 
                    "#366 Impossible\r\n" + 
                    "#367 Impossible\r\n" + 
                    "#368 Impossible\r\n" + 
                    "#369 Possible\r\n" + 
                    "#370 Impossible\r\n" + 
                    "#371 Possible\r\n" + 
                    "#372 Possible\r\n" + 
                    "#373 Impossible\r\n" + 
                    "#374 Possible\r\n" + 
                    "#375 Possible\r\n" + 
                    "#376 Possible\r\n" + 
                    "#377 Impossible\r\n" + 
                    "#378 Impossible\r\n" + 
                    "#379 Possible\r\n" + 
                    "#380 Impossible\r\n" + 
                    "#381 Impossible\r\n" + 
                    "#382 Possible\r\n" + 
                    "#383 Impossible\r\n" + 
                    "#384 Possible\r\n" + 
                    "#385 Impossible\r\n" + 
                    "#386 Impossible\r\n" + 
                    "#387 Possible\r\n" + 
                    "#388 Possible\r\n" + 
                    "#389 Possible\r\n" + 
                    "#390 Possible\r\n" + 
                    "#391 Impossible\r\n" + 
                    "#392 Possible\r\n" + 
                    "#393 Impossible\r\n" + 
                    "#394 Impossible\r\n" + 
                    "#395 Possible\r\n" + 
                    "#396 Possible\r\n" + 
                    "#397 Possible\r\n" + 
                    "#398 Impossible\r\n" + 
                    "#399 Impossible\r\n" + 
                    "#400 Possible\r\n" + 
                    "#401 Possible\r\n" + 
                    "#402 Possible\r\n" + 
                    "#403 Impossible\r\n" + 
                    "#404 Possible\r\n" + 
                    "#405 Possible\r\n" + 
                    "#406 Impossible\r\n" + 
                    "#407 Possible\r\n" + 
                    "#408 Impossible\r\n" + 
                    "#409 Possible\r\n" + 
                    "#410 Impossible\r\n" + 
                    "#411 Impossible\r\n" + 
                    "#412 Impossible\r\n" + 
                    "#413 Impossible\r\n" + 
                    "#414 Possible\r\n" + 
                    "#415 Impossible\r\n" + 
                    "#416 Possible\r\n" + 
                    "#417 Impossible\r\n" + 
                    "#418 Possible\r\n" + 
                    "#419 Impossible\r\n" + 
                    "#420 Impossible\r\n" + 
                    "#421 Possible\r\n" + 
                    "#422 Impossible\r\n" + 
                    "#423 Impossible\r\n" + 
                    "#424 Possible\r\n" + 
                    "#425 Possible\r\n" + 
                    "#426 Impossible\r\n" + 
                    "#427 Impossible\r\n" + 
                    "#428 Impossible\r\n" + 
                    "#429 Impossible\r\n" + 
                    "#430 Impossible\r\n" + 
                    "#431 Impossible\r\n" + 
                    "#432 Impossible\r\n" + 
                    "#433 Possible\r\n" + 
                    "#434 Possible\r\n" + 
                    "#435 Possible\r\n" + 
                    "#436 Impossible\r\n" + 
                    "#437 Impossible\r\n" + 
                    "#438 Possible\r\n" + 
                    "#439 Possible\r\n" + 
                    "#440 Impossible\r\n" + 
                    "#441 Impossible\r\n" + 
                    "#442 Impossible\r\n" + 
                    "#443 Impossible\r\n" + 
                    "#444 Possible\r\n" + 
                    "#445 Impossible\r\n" + 
                    "#446 Impossible\r\n" + 
                    "#447 Possible\r\n" + 
                    "#448 Impossible\r\n" + 
                    "#449 Possible\r\n" + 
                    "#450 Impossible\r\n" + 
                    "#451 Impossible\r\n" + 
                    "#452 Possible\r\n" + 
                    "#453 Impossible\r\n" + 
                    "#454 Possible\r\n" + 
                    "#455 Possible\r\n" + 
                    "#456 Possible\r\n" + 
                    "#457 Possible\r\n" + 
                    "#458 Possible\r\n" + 
                    "#459 Possible\r\n" + 
                    "#460 Impossible\r\n" + 
                    "#461 Possible\r\n" + 
                    "#462 Possible\r\n" + 
                    "#463 Impossible\r\n" + 
                    "#464 Impossible\r\n" + 
                    "#465 Impossible\r\n" + 
                    "#466 Possible\r\n" + 
                    "#467 Impossible\r\n" + 
                    "#468 Possible\r\n" + 
                    "#469 Possible\r\n" + 
                    "#470 Possible\r\n" + 
                    "#471 Impossible\r\n" + 
                    "#472 Possible\r\n" + 
                    "#473 Possible\r\n" + 
                    "#474 Possible\r\n" + 
                    "#475 Impossible\r\n" + 
                    "#476 Possible\r\n" + 
                    "#477 Impossible\r\n" + 
                    "#478 Possible\r\n" + 
                    "#479 Impossible\r\n" + 
                    "#480 Possible\r\n" + 
                    "#481 Possible\r\n" + 
                    "#482 Possible\r\n" + 
                    "#483 Possible\r\n" + 
                    "#484 Possible\r\n" + 
                    "#485 Impossible\r\n" + 
                    "#486 Possible\r\n" + 
                    "#487 Impossible\r\n" + 
                    "#488 Impossible\r\n" + 
                    "#489 Impossible\r\n" + 
                    "#490 Possible\r\n" + 
                    "#491 Possible\r\n" + 
                    "#492 Impossible\r\n" + 
                    "#493 Impossible\r\n" + 
                    "#494 Possible\r\n" + 
                    "#495 Impossible\r\n" + 
                    "#496 Possible\r\n" + 
                    "#497 Impossible\r\n" + 
                    "#498 Impossible\r\n" + 
                    "#499 Impossible\r\n" + 
                    "#500 Impossible\r\n" + 
                    "#501 Possible\r\n" + 
                    "#502 Possible\r\n" + 
                    "#503 Impossible\r\n" + 
                    "#504 Possible\r\n" + 
                    "#505 Impossible\r\n" + 
                    "#506 Impossible\r\n" + 
                    "#507 Possible\r\n" + 
                    "#508 Impossible\r\n" + 
                    "#509 Impossible\r\n" + 
                    "#510 Possible\r\n" + 
                    "#511 Impossible\r\n" + 
                    "#512 Impossible\r\n" + 
                    "#513 Possible\r\n" + 
                    "#514 Possible\r\n" + 
                    "#515 Impossible\r\n" + 
                    "#516 Impossible\r\n" + 
                    "#517 Impossible\r\n" + 
                    "#518 Impossible\r\n" + 
                    "#519 Impossible\r\n" + 
                    "#520 Impossible\r\n" + 
                    "#521 Possible\r\n" + 
                    "#522 Impossible\r\n" + 
                    "#523 Impossible\r\n" + 
                    "#524 Impossible\r\n" + 
                    "#525 Impossible\r\n" + 
                    "#526 Possible\r\n" + 
                    "#527 Impossible\r\n" + 
                    "#528 Impossible\r\n" + 
                    "#529 Possible\r\n" + 
                    "#530 Impossible\r\n" + 
                    "#531 Impossible\r\n" + 
                    "#532 Impossible\r\n" + 
                    "#533 Impossible\r\n" + 
                    "#534 Impossible\r\n" + 
                    "#535 Impossible\r\n" + 
                    "#536 Impossible\r\n" + 
                    "#537 Possible\r\n" + 
                    "#538 Possible\r\n" + 
                    "#539 Possible\r\n" + 
                    "#540 Impossible\r\n" + 
                    "#541 Possible\r\n" + 
                    "#542 Impossible\r\n" + 
                    "#543 Possible\r\n" + 
                    "#544 Possible\r\n" + 
                    "#545 Impossible\r\n" + 
                    "#546 Possible\r\n" + 
                    "#547 Impossible\r\n" + 
                    "#548 Impossible\r\n" + 
                    "#549 Possible\r\n" + 
                    "#550 Possible\r\n" + 
                    "#551 Impossible\r\n" + 
                    "#552 Impossible\r\n" + 
                    "#553 Impossible\r\n" + 
                    "#554 Impossible\r\n" + 
                    "#555 Possible\r\n" + 
                    "#556 Impossible\r\n" + 
                    "#557 Possible\r\n" + 
                    "#558 Possible\r\n" + 
                    "#559 Possible\r\n" + 
                    "#560 Impossible\r\n" + 
                    "#561 Impossible\r\n" + 
                    "#562 Possible\r\n" + 
                    "#563 Impossible\r\n" + 
                    "#564 Impossible\r\n" + 
                    "#565 Possible\r\n" + 
                    "#566 Impossible\r\n" + 
                    "#567 Impossible\r\n" + 
                    "#568 Impossible\r\n" + 
                    "#569 Possible\r\n" + 
                    "#570 Impossible\r\n" + 
                    "#571 Impossible\r\n" + 
                    "#572 Impossible\r\n" + 
                    "#573 Possible\r\n" + 
                    "#574 Possible\r\n" + 
                    "#575 Impossible\r\n" + 
                    "#576 Possible\r\n" + 
                    "#577 Impossible\r\n" + 
                    "#578 Possible\r\n" + 
                    "#579 Possible\r\n" + 
                    "#580 Impossible\r\n" + 
                    "#581 Impossible\r\n" + 
                    "#582 Impossible\r\n" + 
                    "#583 Impossible\r\n" + 
                    "#584 Possible\r\n" + 
                    "#585 Impossible\r\n" + 
                    "#586 Impossible\r\n" + 
                    "#587 Possible\r\n" + 
                    "#588 Possible\r\n" + 
                    "#589 Impossible\r\n" + 
                    "#590 Impossible\r\n" + 
                    "#591 Impossible\r\n" + 
                    "#592 Possible\r\n" + 
                    "#593 Impossible\r\n" + 
                    "#594 Impossible\r\n" + 
                    "#595 Possible\r\n" + 
                    "#596 Impossible\r\n" + 
                    "#597 Possible\r\n" + 
                    "#598 Impossible\r\n" + 
                    "#599 Impossible\r\n" + 
                    "#600 Impossible\r\n" + 
                    "#601 Impossible\r\n" + 
                    "#602 Impossible\r\n" + 
                    "#603 Possible\r\n" + 
                    "#604 Impossible\r\n" + 
                    "#605 Possible\r\n" + 
                    "#606 Impossible\r\n" + 
                    "#607 Impossible\r\n" + 
                    "#608 Impossible\r\n" + 
                    "#609 Impossible\r\n" + 
                    "#610 Impossible\r\n" + 
                    "#611 Impossible\r\n" + 
                    "#612 Impossible\r\n" + 
                    "#613 Possible\r\n" + 
                    "#614 Possible\r\n" + 
                    "#615 Possible\r\n" + 
                    "#616 Impossible\r\n" + 
                    "#617 Impossible\r\n" + 
                    "#618 Impossible\r\n" + 
                    "#619 Possible\r\n" + 
                    "#620 Impossible\r\n" + 
                    "#621 Possible\r\n" + 
                    "#622 Impossible\r\n" + 
                    "#623 Impossible\r\n" + 
                    "#624 Impossible\r\n" + 
                    "#625 Possible\r\n" + 
                    "#626 Possible\r\n" + 
                    "#627 Impossible\r\n" + 
                    "#628 Impossible\r\n" + 
                    "#629 Impossible\r\n" + 
                    "#630 Impossible\r\n" + 
                    "#631 Possible\r\n" + 
                    "#632 Impossible\r\n" + 
                    "#633 Possible\r\n" + 
                    "#634 Impossible\r\n" + 
                    "#635 Possible\r\n" + 
                    "#636 Impossible\r\n" + 
                    "#637 Possible\r\n" + 
                    "#638 Impossible\r\n" + 
                    "#639 Impossible\r\n" + 
                    "#640 Possible\r\n" + 
                    "#641 Possible\r\n" + 
                    "#642 Possible\r\n" + 
                    "#643 Impossible\r\n" + 
                    "#644 Impossible\r\n" + 
                    "#645 Impossible\r\n" + 
                    "#646 Possible\r\n" + 
                    "#647 Possible\r\n" + 
                    "#648 Possible\r\n" + 
                    "#649 Impossible\r\n" + 
                    "#650 Impossible\r\n" + 
                    "#651 Impossible\r\n" + 
                    "#652 Possible\r\n" + 
                    "#653 Impossible\r\n" + 
                    "#654 Possible\r\n" + 
                    "#655 Possible\r\n" + 
                    "#656 Possible\r\n" + 
                    "#657 Possible\r\n" + 
                    "#658 Impossible\r\n" + 
                    "#659 Possible\r\n" + 
                    "#660 Possible\r\n" + 
                    "#661 Impossible\r\n" + 
                    "#662 Impossible\r\n" + 
                    "#663 Impossible\r\n" + 
                    "#664 Possible\r\n" + 
                    "#665 Impossible\r\n" + 
                    "#666 Impossible\r\n" + 
                    "#667 Possible\r\n" + 
                    "#668 Possible\r\n" + 
                    "#669 Impossible\r\n" + 
                    "#670 Possible\r\n" + 
                    "#671 Possible\r\n" + 
                    "#672 Possible\r\n" + 
                    "#673 Possible\r\n" + 
                    "#674 Possible\r\n" + 
                    "#675 Possible\r\n" + 
                    "#676 Impossible\r\n" + 
                    "#677 Possible\r\n" + 
                    "#678 Impossible\r\n" + 
                    "#679 Impossible\r\n" + 
                    "#680 Possible\r\n" + 
                    "#681 Impossible\r\n" + 
                    "#682 Possible\r\n" + 
                    "#683 Impossible\r\n" + 
                    "#684 Possible\r\n" + 
                    "#685 Impossible\r\n" + 
                    "#686 Impossible\r\n" + 
                    "#687 Impossible\r\n" + 
                    "#688 Possible\r\n" + 
                    "#689 Possible\r\n" + 
                    "#690 Possible\r\n" + 
                    "#691 Impossible\r\n" + 
                    "#692 Possible\r\n" + 
                    "#693 Possible\r\n" + 
                    "#694 Impossible\r\n" + 
                    "#695 Possible\r\n" + 
                    "#696 Possible\r\n" + 
                    "#697 Possible\r\n" + 
                    "#698 Impossible\r\n" + 
                    "#699 Possible\r\n" + 
                    "#700 Possible\r\n" + 
                    "#701 Possible\r\n" + 
                    "#702 Possible\r\n" + 
                    "#703 Possible\r\n" + 
                    "#704 Possible\r\n" + 
                    "#705 Impossible\r\n" + 
                    "#706 Impossible\r\n" + 
                    "#707 Possible\r\n" + 
                    "#708 Impossible\r\n" + 
                    "#709 Impossible\r\n" + 
                    "#710 Possible\r\n" + 
                    "#711 Possible\r\n" + 
                    "#712 Impossible\r\n" + 
                    "#713 Impossible\r\n" + 
                    "#714 Impossible\r\n" + 
                    "#715 Impossible\r\n" + 
                    "#716 Impossible\r\n" + 
                    "#717 Impossible\r\n" + 
                    "#718 Possible\r\n" + 
                    "#719 Impossible\r\n" + 
                    "#720 Possible\r\n" + 
                    "#721 Possible\r\n" + 
                    "#722 Impossible\r\n" + 
                    "#723 Possible\r\n" + 
                    "#724 Impossible\r\n" + 
                    "#725 Possible\r\n" + 
                    "#726 Impossible\r\n" + 
                    "#727 Impossible\r\n" + 
                    "#728 Possible\r\n" + 
                    "#729 Possible\r\n" + 
                    "#730 Impossible\r\n" + 
                    "#731 Impossible\r\n" + 
                    "#732 Possible\r\n" + 
                    "#733 Impossible\r\n" + 
                    "#734 Impossible\r\n" + 
                    "#735 Possible\r\n" + 
                    "#736 Impossible\r\n" + 
                    "#737 Possible\r\n" + 
                    "#738 Impossible\r\n" + 
                    "#739 Possible\r\n" + 
                    "#740 Impossible\r\n" + 
                    "#741 Impossible\r\n" + 
                    "#742 Impossible\r\n" + 
                    "#743 Impossible\r\n" + 
                    "#744 Impossible\r\n" + 
                    "#745 Impossible\r\n" + 
                    "#746 Possible\r\n" + 
                    "#747 Impossible\r\n" + 
                    "#748 Possible\r\n" + 
                    "#749 Possible\r\n" + 
                    "#750 Impossible\r\n" + 
                    "#751 Possible\r\n" + 
                    "#752 Impossible\r\n" + 
                    "#753 Impossible\r\n" + 
                    "#754 Impossible\r\n" + 
                    "#755 Impossible\r\n" + 
                    "#756 Possible\r\n" + 
                    "#757 Possible\r\n" + 
                    "#758 Impossible\r\n" + 
                    "#759 Impossible\r\n" + 
                    "#760 Impossible\r\n" + 
                    "#761 Impossible\r\n" + 
                    "#762 Impossible\r\n" + 
                    "#763 Impossible\r\n" + 
                    "#764 Impossible\r\n" + 
                    "#765 Impossible\r\n" + 
                    "#766 Possible\r\n" + 
                    "#767 Impossible\r\n" + 
                    "#768 Possible\r\n" + 
                    "#769 Possible\r\n" + 
                    "#770 Impossible\r\n" + 
                    "#771 Impossible\r\n" + 
                    "#772 Impossible\r\n" + 
                    "#773 Impossible\r\n" + 
                    "#774 Possible\r\n" + 
                    "#775 Possible\r\n" + 
                    "#776 Possible\r\n" + 
                    "#777 Possible\r\n" + 
                    "#778 Impossible\r\n" + 
                    "#779 Impossible\r\n" + 
                    "#780 Impossible\r\n" + 
                    "#781 Possible\r\n" + 
                    "#782 Impossible\r\n" + 
                    "#783 Impossible\r\n" + 
                    "#784 Possible\r\n" + 
                    "#785 Impossible\r\n" + 
                    "#786 Possible\r\n" + 
                    "#787 Impossible\r\n" + 
                    "#788 Possible\r\n" + 
                    "#789 Impossible\r\n" + 
                    "#790 Possible\r\n" + 
                    "#791 Impossible\r\n" + 
                    "#792 Impossible\r\n" + 
                    "#793 Possible\r\n" + 
                    "#794 Impossible\r\n" + 
                    "#795 Possible\r\n" + 
                    "#796 Possible\r\n" + 
                    "#797 Impossible\r\n" + 
                    "#798 Impossible\r\n" + 
                    "#799 Impossible\r\n" + 
                    "#800 Possible\r\n" + 
                    "#801 Possible\r\n" + 
                    "#802 Impossible\r\n" + 
                    "#803 Possible\r\n" + 
                    "#804 Impossible\r\n" + 
                    "#805 Impossible\r\n" + 
                    "#806 Possible\r\n" + 
                    "#807 Possible\r\n" + 
                    "#808 Possible\r\n" + 
                    "#809 Impossible\r\n" + 
                    "#810 Impossible\r\n" + 
                    "#811 Impossible\r\n" + 
                    "#812 Possible\r\n" + 
                    "#813 Impossible\r\n" + 
                    "#814 Possible\r\n" + 
                    "#815 Impossible\r\n" + 
                    "#816 Possible\r\n" + 
                    "#817 Possible\r\n" + 
                    "#818 Impossible\r\n" + 
                    "#819 Possible\r\n" + 
                    "#820 Impossible\r\n" + 
                    "#821 Impossible\r\n" + 
                    "#822 Impossible\r\n" + 
                    "#823 Impossible\r\n" + 
                    "#824 Impossible\r\n" + 
                    "#825 Impossible\r\n" + 
                    "#826 Impossible\r\n" + 
                    "#827 Possible\r\n" + 
                    "#828 Impossible\r\n" + 
                    "#829 Impossible\r\n" + 
                    "#830 Possible\r\n" + 
                    "#831 Possible\r\n" + 
                    "#832 Impossible\r\n" + 
                    "#833 Possible\r\n" + 
                    "#834 Impossible\r\n" + 
                    "#835 Possible\r\n" + 
                    "#836 Impossible\r\n" + 
                    "#837 Possible\r\n" + 
                    "#838 Possible\r\n" + 
                    "#839 Possible\r\n" + 
                    "#840 Impossible\r\n" + 
                    "#841 Possible\r\n" + 
                    "#842 Possible\r\n" + 
                    "#843 Impossible\r\n" + 
                    "#844 Possible\r\n" + 
                    "#845 Impossible\r\n" + 
                    "#846 Possible\r\n" + 
                    "#847 Possible\r\n" + 
                    "#848 Impossible\r\n" + 
                    "#849 Impossible\r\n" + 
                    "#850 Impossible\r\n" + 
                    "#851 Impossible\r\n" + 
                    "#852 Impossible\r\n" + 
                    "#853 Impossible\r\n" + 
                    "#854 Impossible\r\n" + 
                    "#855 Impossible\r\n" + 
                    "#856 Possible\r\n" + 
                    "#857 Possible\r\n" + 
                    "#858 Impossible\r\n" + 
                    "#859 Possible\r\n" + 
                    "#860 Impossible\r\n" + 
                    "#861 Possible\r\n" + 
                    "#862 Impossible\r\n" + 
                    "#863 Impossible\r\n" + 
                    "#864 Impossible\r\n" + 
                    "#865 Possible\r\n" + 
                    "#866 Possible\r\n" + 
                    "#867 Impossible\r\n" + 
                    "#868 Impossible\r\n" + 
                    "#869 Impossible\r\n" + 
                    "#870 Possible\r\n" + 
                    "#871 Possible\r\n" + 
                    "#872 Possible\r\n" + 
                    "#873 Possible\r\n" + 
                    "#874 Possible\r\n" + 
                    "#875 Possible\r\n" + 
                    "#876 Impossible\r\n" + 
                    "#877 Possible\r\n" + 
                    "#878 Impossible\r\n" + 
                    "#879 Possible\r\n" + 
                    "#880 Impossible\r\n" + 
                    "#881 Impossible\r\n" + 
                    "#882 Impossible\r\n" + 
                    "#883 Impossible\r\n" + 
                    "#884 Possible\r\n" + 
                    "#885 Impossible\r\n" + 
                    "#886 Impossible\r\n" + 
                    "#887 Possible\r\n" + 
                    "#888 Possible\r\n" + 
                    "#889 Impossible\r\n" + 
                    "#890 Possible\r\n" + 
                    "#891 Impossible\r\n" + 
                    "#892 Impossible\r\n" + 
                    "#893 Possible\r\n" + 
                    "#894 Possible\r\n" + 
                    "#895 Impossible\r\n" + 
                    "#896 Possible\r\n" + 
                    "#897 Impossible\r\n" + 
                    "#898 Possible\r\n" + 
                    "#899 Impossible\r\n" + 
                    "#900 Impossible\r\n" + 
                    "#901 Impossible\r\n" + 
                    "#902 Possible\r\n" + 
                    "#903 Impossible\r\n" + 
                    "#904 Impossible\r\n" + 
                    "#905 Possible\r\n" + 
                    "#906 Impossible\r\n" + 
                    "#907 Possible\r\n" + 
                    "#908 Possible\r\n" + 
                    "#909 Impossible\r\n" + 
                    "#910 Possible\r\n" + 
                    "#911 Impossible\r\n" + 
                    "#912 Impossible\r\n" + 
                    "#913 Impossible\r\n" + 
                    "#914 Possible\r\n" + 
                    "#915 Possible\r\n" + 
                    "#916 Possible\r\n" + 
                    "#917 Possible\r\n" + 
                    "#918 Possible\r\n" + 
                    "#919 Possible\r\n" + 
                    "#920 Impossible\r\n" + 
                    "#921 Impossible\r\n" + 
                    "#922 Possible\r\n" + 
                    "#923 Impossible\r\n" + 
                    "#924 Impossible\r\n" + 
                    "#925 Possible\r\n" + 
                    "#926 Impossible\r\n" + 
                    "#927 Impossible\r\n" + 
                    "#928 Possible\r\n" + 
                    "#929 Possible\r\n" + 
                    "#930 Possible\r\n" + 
                    "#931 Possible\r\n" + 
                    "#932 Impossible\r\n" + 
                    "#933 Impossible\r\n" + 
                    "#934 Possible\r\n" + 
                    "#935 Possible\r\n" + 
                    "#936 Possible\r\n" + 
                    "#937 Possible\r\n" + 
                    "#938 Impossible\r\n" + 
                    "#939 Impossible\r\n" + 
                    "#940 Impossible\r\n" + 
                    "#941 Possible\r\n" + 
                    "#942 Possible\r\n" + 
                    "#943 Impossible\r\n" + 
                    "#944 Possible\r\n" + 
                    "#945 Impossible\r\n" + 
                    "#946 Impossible\r\n" + 
                    "#947 Possible\r\n" + 
                    "#948 Impossible\r\n" + 
                    "#949 Impossible\r\n" + 
                    "#950 Possible\r\n" + 
                    "#951 Impossible\r\n" + 
                    "#952 Possible\r\n" + 
                    "#953 Impossible\r\n" + 
                    "#954 Possible\r\n" + 
                    "#955 Impossible\r\n" + 
                    "#956 Impossible\r\n" + 
                    "#957 Possible\r\n" + 
                    "#958 Impossible\r\n" + 
                    "#959 Impossible\r\n" + 
                    "#960 Impossible\r\n" + 
                    "#961 Possible\r\n" + 
                    "#962 Possible\r\n" + 
                    "#963 Possible\r\n" + 
                    "#964 Impossible\r\n" + 
                    "#965 Possible\r\n" + 
                    "#966 Possible\r\n" + 
                    "#967 Impossible\r\n" + 
                    "#968 Possible\r\n" + 
                    "#969 Impossible\r\n" + 
                    "#970 Possible\r\n" + 
                    "#971 Impossible\r\n" + 
                    "#972 Possible\r\n" + 
                    "#973 Impossible\r\n" + 
                    "#974 Possible\r\n" + 
                    "#975 Impossible\r\n" + 
                    "#976 Impossible\r\n" + 
                    "#977 Possible\r\n" + 
                    "#978 Impossible\r\n" + 
                    "#979 Impossible\r\n" + 
                    "#980 Possible\r\n" + 
                    "#981 Impossible\r\n" + 
                    "#982 Possible\r\n" + 
                    "#983 Possible\r\n" + 
                    "#984 Possible\r\n" + 
                    "#985 Impossible\r\n" + 
                    "#986 Possible\r\n" + 
                    "#987 Possible\r\n" + 
                    "#988 Possible\r\n" + 
                    "#989 Possible\r\n" + 
                    "#990 Impossible\r\n" + 
                    "#991 Impossible\r\n" + 
                    "#992 Impossible\r\n" + 
                    "#993 Impossible\r\n" + 
                    "#994 Possible\r\n" + 
                    "#995 Possible\r\n" + 
                    "#996 Impossible\r\n" + 
                    "#997 Possible\r\n" + 
                    "#998 Possible\r\n" + 
                    "#999 Impossible\r\n" + 
                    "#1000 Impossible\r\n" + 
                    "");
        }
    }
}